import random
import unittest
from itertools import product

from support import load

R = load("experiments/n2/rank_law.py", "rank_law_nondeg")
C = R.C
GUARDS_CLAIM = "RankLawNondegenerate"
GUARDS_CONTRACT = "QuaternionDoubling identities hold in the cayley-dickson/v1 octonion model over F_ell"


def mat_mul(a, b, ell):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(2)) % ell for j in range(2)) for i in range(2))


def generated_dimension(a, b, ell):
    """Dimension of the unital subalgebra of M_2(F_ell) generated by a and b (closure under products)."""
    span = [((1, 0), (0, 1)), a, b]
    while True:
        words = span + [mat_mul(u, v, ell) for u in span for v in span]
        basis = []
        for w in words:
            flat = [t for row in w for t in row]
            if C.rank(basis + [flat], ell) > len(basis):
                basis.append(flat)
        if len(basis) == len(span) or len(basis) == 4:
            return len(basis)
        span = [((f[0], f[1]), (f[2], f[3])) for f in basis]


def combination(vectors, coeffs, ell):
    return tuple(sum(c * v[i] for c, v in zip(coeffs, vectors)) % ell for i in range(C.DIM))


def sub(u, v, ell):
    return tuple((s - t) % ell for s, t in zip(u, v))


class TestCommutatorLemma(unittest.TestCase):
    def test_singular_commutator_bounds_the_generated_algebra_exhaustively_over_f3(self):
        """Lemma 3.11 on all 81^2 pairs in M_2(F_3); the converse direction is checked too."""
        ell = 3
        mats = [((a, b), (c, d)) for a, b, c, d in product(range(ell), repeat=4)]
        for a in mats:
            for b in mats:
                comm = tuple(tuple((s - t) % ell for s, t in zip(r1, r2))
                             for r1, r2 in zip(mat_mul(a, b, ell), mat_mul(b, a, ell)))
                singular = (comm[0][0] * comm[1][1] - comm[0][1] * comm[1][0]) % ell == 0
                self.assertEqual(singular, generated_dimension(a, b, ell) <= 3)


class TestNondegenerateCase(unittest.TestCase):
    def cases(self, ell, count, seed):
        rng = random.Random(seed)
        found = 0
        while found < count:
            x, y = (tuple(rng.randrange(ell) for _ in range(C.DIM)) for _ in range(2))
            xy = C.mul(x, y, ell)
            q = [C.BASIS[0], x, y, xy]
            if C.rank(q, ell) != 4 or not R.gram_nondegenerate(q, ell):
                continue
            perp = R.orthogonal_complement(q, ell)
            v = next((w for w in (combination(perp, [rng.randrange(ell) for _ in perp], ell) for _ in range(50))
                      if C.norm(w, ell)), None)
            if v is not None:
                found += 1
                yield x, y, xy, q, v, rng

    def test_doubling_kernel_and_commutator(self):
        for ell in (3, 5, 7):
            for x, y, xy, q, v, rng in self.cases(ell, 40, ell):
                with self.subTest(ell=ell, x=x, y=y):
                    self.assertTrue(all(R.bilinear(w, v, ell) == 0 for w in q))
                    c = sub(C.mul(y, x, ell), xy, ell)
                    self.assertNotEqual(C.norm(c, ell), 0)
                    for _ in range(4):
                        a, b = (combination(q, [rng.randrange(ell) for _ in q], ell) for _ in range(2))
                        self.assertEqual(C.mul(a, C.mul(b, v, ell), ell), C.mul(C.mul(b, a, ell), v, ell))
                        uv = C.mul(b, v, ell)
                        assoc = sub(C.mul(x, C.mul(y, uv, ell), ell), C.mul(xy, uv, ell), ell)
                        self.assertEqual(assoc, C.mul(C.mul(b, c, ell), v, ell))
                    phi = R.matsub(C.matmul(C.left(x, ell), C.left(y, ell), ell), C.left(xy, ell), ell)
                    self.assertEqual(C.rank(phi, ell), 4)


if __name__ == "__main__":
    unittest.main()
