#!/usr/bin/env python3
"""Generate the paper's data tables from committed repository data; never edit tables/ by hand.

Sources:
  data/n2/defect-census-v1.json   -> tables/census.tex
  data/n2/oracle-mutants-v1.json  -> tables/mutants.tex

Usage: make_tables.py [--check]
"""
from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CENSUS = ROOT / "data" / "n2" / "defect-census-v1.json"
MUTANTS = ROOT / "data" / "n2" / "oracle-mutants-v1.json"
HEADER = "% Generated by paper/associator-defects/make_tables.py from {src}; do not edit.\n"

# Self-check names grouped into the check families of Section 5.
FAMILIES = (
    ("Closure", "pentagon boundary closes"),
    ("Replay", "edges replay the Python experiment"),
    ("Vertex", "each edge is its vertex difference"),
    ("Sign flip", "sign-flip mutants are killed"),
    ("$\\mathbb F_3$", "F3 "),
)

# Display names of the mutants in scripts/lean_mutation_suite.py; an unmapped mutant is an error.
MUTANT_TEX = {
    "drop sign of [a,b,cd]": "$e_3 = [a,b,cd]$ (sign dropped)",
    "d[a,b,c] for [a,b,c]d": "$e_0 = d\\,[a,b,c]$ (factor side)",
    "[bc,a,d] for [a,bc,d]": "$e_1 = [bc,a,d]$ (argument order)",
    "negated associator": "$[x,y,z] = (xy)z - x(yz)$ (global sign)",
    "(ba) for (ab) in [ab,c,d]": "$e_4 = -[ba,c,d]$ (inner order)",
    "transposed tensor": "$t_{ijk} \\mapsto t_{jik}$ (opposite algebra)",
}


def census_table() -> str:
    data = json.loads(CENSUS.read_text(encoding="utf-8"))
    lines = [HEADER.format(src="data/n2/defect-census-v1.json"),
             "\\begin{tabular}{rrcccrr}", "\\toprule",
             " & & \\multicolumn{3}{c}{$(\\dim Q,\\ \\operatorname{rank}(\\Delta-I))$} & distinct "
             "$\\operatorname{tr}\\Delta$ & \\\\",
             "\\cmidrule(lr){3-5}",
             "$\\ell$ & pairs & $(2,0)$ & $(3,2)$ & $(4,4)$ & at $\\dim Q=4$ & violations \\\\", "\\midrule"]
    for row in data["rows"]:
        by = Counter()
        traces = set()
        for s in row["strata"]:
            by[(s["dim_Q"], s["rank_moved"])] += s["count"]
            if s["dim_Q"] == 4:
                traces.add(s["trace"])
        other = sum(c for k, c in by.items() if k not in {(2, 0), (3, 2), (4, 4)})
        if other:
            raise ValueError(f"ell={row['ell']}: strata outside the rank law: {by}")
        lines.append(f"{row['ell']} & {row['pairs']} & {by[(2, 0)]} & {by[(3, 2)]} & {by[(4, 4)]} & "
                     f"{len(traces)} & {sum(row['violations'].values())} \\\\")
    return "\n".join(lines + ["\\bottomrule", "\\end{tabular}", ""])


def mutant_table() -> str:
    data = json.loads(MUTANTS.read_text(encoding="utf-8"))
    cols = "l" + "c" * len(FAMILIES) + "r"
    lines = [HEADER.format(src="data/n2/oracle-mutants-v1.json"),
             f"\\begin{{tabular}}{{{cols}}}", "\\toprule",
             "Mutant of \\texttt{Oracle.lean} & " + " & ".join(f for f, _ in FAMILIES) + " & failing checks \\\\",
             "\\midrule"]
    for m in data["mutants"]:
        if not m["killed"]:
            raise ValueError(f"mutant survived: {m['mutant']}")
        hits = defaultdict(int)
        for check in m["failing_checks"]:
            for family, marker in FAMILIES:
                hits[family] += marker in check
        marks = " & ".join("$\\bullet$" if hits[f] else "" for f, _ in FAMILIES)
        lines.append(f"{MUTANT_TEX[m['mutant']]} & {marks} & {len(m['failing_checks'])} \\\\")
    return "\n".join(lines + ["\\bottomrule", "\\end{tabular}", ""])


TABLES = {"census.tex": census_table, "mutants.tex": mutant_table}


def main(argv: list[str]) -> int:
    stale = []
    for name, render in TABLES.items():
        path, text = HERE / "tables" / name, render()
        if argv[1:] == ["--check"]:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8")
    if stale:
        print("stale tables: " + ", ".join(stale))
        return 1
    print("OK: paper tables are current" if argv[1:] == ["--check"] else "wrote paper tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
