---- MODULE MCNoveltyLedgerOpen ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
EXTENDS NoveltyLedger

Reachable == {
    "HurwitzShellCountFinite",
    "RankLawExhaustiveF3"
}
EventuallyReachable == <>(established = Reachable)
====
