---- MODULE MCNoveltyLedgerImports ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
EXTENDS NoveltyLedger

Reachable == {
    "ArtinTheorem",
    "CliffordSpinTrace",
    "CompositionDimensions",
    "CompositionIdentities",
    "HurwitzShellCountFinite",
    "MoufangTheorem",
    "QuaternionDoubling",
    "RankLawExhaustiveF3",
    "WallConjugacy",
    "WordDefectNotClassical",
    "ZornPeirce"
}
EventuallyReachable == <>(established = Reachable)
====
