---- MODULE MCNoveltyLedgerImports ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
EXTENDS NoveltyLedger

Reachable == {
    "ArtinTheorem",
    "CompositionIdentities",
    "HurwitzShellCountFinite",
    "QuaternionDoubling",
    "RankLawExhaustiveF3"
}
EventuallyReachable == <>(established = Reachable)
====
