---- MODULE NoveltyLedger ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
(* Repository: larsbx/novelty-lab. *)
(* Results are named proof records. Requires is one-way dependency, never a *)
(* converse implication. ProvedDef holds the accepted in-repository records, *)
(* ImportedDef the accepted imported theorems, BoundedDef the bounded        *)
(* experiments, WithdrawnDef the withdrawn claims.                           *)
EXTENDS ProofArchitecture

ResultSet == {
    "ArtinTheorem",
    "AssociativeSubalgebraBound",
    "CliffordSpinTrace",
    "CompositionDimensions",
    "CompositionIdentities",
    "DefectCensus",
    "DefectCharacteristicPolynomial",
    "DefectClassGramAndDimQ",
    "DefectClassIsClassical",
    "DefectFixesQuaternionSubalgebra",
    "DefectJordanType",
    "DefectRankLaw",
    "DefectReflectionFactorization",
    "DefectSOClassFinite",
    "DefectSpecialOrthogonal",
    "DefectStratifiedCollisions",
    "DivisionCertificateSoundness",
    "H3PilotCollisions",
    "HilbertSymbolFormula",
    "HurwitzShellCount",
    "HurwitzShellCountFinite",
    "MoufangTheorem",
    "N3BaselineGrid",
    "N3PoissonHeuristic",
    "QuaternionDoubling",
    "QuaternionSplitIffConic",
    "RankLawDegenerate",
    "RankLawExhaustiveF3",
    "RankLawNondegenerate",
    "WallConjugacy",
    "WordDefectEquivariance",
    "WordDefectG2Data",
    "WordDefectLengthThreeClassical",
    "WordDefectNotClassical",
    "ZeroDivisorCertificateSoundness",
    "ZornPeirce"
}

RequiresDef == [r \in ResultSet |->
    CASE r = "ArtinTheorem" -> {}
      [] r = "AssociativeSubalgebraBound" -> {"CompositionIdentities", "CompositionDimensions", "ZornPeirce", "RankLawNondegenerate"}
      [] r = "CliffordSpinTrace" -> {}
      [] r = "CompositionDimensions" -> {}
      [] r = "CompositionIdentities" -> {}
      [] r = "DefectCensus" -> {}
      [] r = "DefectCharacteristicPolynomial" -> {"CompositionIdentities", "QuaternionDoubling"}
      [] r = "DefectClassGramAndDimQ" -> {"DefectJordanType", "DefectClassIsClassical", "CompositionIdentities"}
      [] r = "DefectClassIsClassical" -> {"DefectCharacteristicPolynomial", "CompositionIdentities"}
      [] r = "DefectFixesQuaternionSubalgebra" -> {"CompositionIdentities", "ArtinTheorem"}
      [] r = "DefectJordanType" -> {"DefectCharacteristicPolynomial", "RankLawDegenerate", "AssociativeSubalgebraBound", "CompositionIdentities"}
      [] r = "DefectRankLaw" -> {"DefectFixesQuaternionSubalgebra", "RankLawDegenerate"}
      [] r = "DefectReflectionFactorization" -> {"QuaternionDoubling", "DefectCharacteristicPolynomial"}
      [] r = "DefectSOClassFinite" -> {"DefectReflectionFactorization", "DefectClassIsClassical", "WallConjugacy"}
      [] r = "DefectSpecialOrthogonal" -> {}
      [] r = "DefectStratifiedCollisions" -> {}
      [] r = "DivisionCertificateSoundness" -> {"HilbertSymbolFormula", "QuaternionSplitIffConic"}
      [] r = "H3PilotCollisions" -> {}
      [] r = "HilbertSymbolFormula" -> {}
      [] r = "HurwitzShellCount" -> {}
      [] r = "HurwitzShellCountFinite" -> {}
      [] r = "MoufangTheorem" -> {}
      [] r = "N3BaselineGrid" -> {}
      [] r = "N3PoissonHeuristic" -> {}
      [] r = "QuaternionDoubling" -> {}
      [] r = "QuaternionSplitIffConic" -> {}
      [] r = "RankLawDegenerate" -> {"MoufangTheorem", "ArtinTheorem", "CompositionIdentities", "AssociativeSubalgebraBound"}
      [] r = "RankLawExhaustiveF3" -> {}
      [] r = "RankLawNondegenerate" -> {"CompositionIdentities", "QuaternionDoubling"}
      [] r = "WallConjugacy" -> {}
      [] r = "WordDefectEquivariance" -> {"CompositionIdentities"}
      [] r = "WordDefectG2Data" -> {}
      [] r = "WordDefectLengthThreeClassical" -> {"CliffordSpinTrace", "CompositionIdentities"}
      [] r = "WordDefectNotClassical" -> {}
      [] r = "ZeroDivisorCertificateSoundness" -> {}
      [] r = "ZornPeirce" -> {}]

ProvedDef == {
    "HurwitzShellCountFinite",
    "RankLawExhaustiveF3",
    "WordDefectNotClassical"
}

ImportedDef == {
    "ArtinTheorem",
    "CliffordSpinTrace",
    "CompositionDimensions",
    "CompositionIdentities",
    "MoufangTheorem",
    "QuaternionDoubling",
    "WallConjugacy",
    "ZornPeirce"
}

BoundedDef == {
    "DefectCensus",
    "H3PilotCollisions",
    "N3BaselineGrid",
    "WordDefectG2Data"
}

WithdrawnDef == {}

NoAssumptions == {}
ImportsAssumed == ImportedDef

(* Observables: one per result, asserting that it is not established. A model *)
(* lists those its assumptions leave unreachable; TLC then checks the closure.  *)
ArtinTheoremNotEstablished == "ArtinTheorem" \notin established
AssociativeSubalgebraBoundNotEstablished == "AssociativeSubalgebraBound" \notin established
CliffordSpinTraceNotEstablished == "CliffordSpinTrace" \notin established
CompositionDimensionsNotEstablished == "CompositionDimensions" \notin established
CompositionIdentitiesNotEstablished == "CompositionIdentities" \notin established
DefectCensusNotEstablished == "DefectCensus" \notin established
DefectCharacteristicPolynomialNotEstablished == "DefectCharacteristicPolynomial" \notin established
DefectClassGramAndDimQNotEstablished == "DefectClassGramAndDimQ" \notin established
DefectClassIsClassicalNotEstablished == "DefectClassIsClassical" \notin established
DefectFixesQuaternionSubalgebraNotEstablished == "DefectFixesQuaternionSubalgebra" \notin established
DefectJordanTypeNotEstablished == "DefectJordanType" \notin established
DefectRankLawNotEstablished == "DefectRankLaw" \notin established
DefectReflectionFactorizationNotEstablished == "DefectReflectionFactorization" \notin established
DefectSOClassFiniteNotEstablished == "DefectSOClassFinite" \notin established
DefectSpecialOrthogonalNotEstablished == "DefectSpecialOrthogonal" \notin established
DefectStratifiedCollisionsNotEstablished == "DefectStratifiedCollisions" \notin established
DivisionCertificateSoundnessNotEstablished == "DivisionCertificateSoundness" \notin established
H3PilotCollisionsNotEstablished == "H3PilotCollisions" \notin established
HilbertSymbolFormulaNotEstablished == "HilbertSymbolFormula" \notin established
HurwitzShellCountNotEstablished == "HurwitzShellCount" \notin established
HurwitzShellCountFiniteNotEstablished == "HurwitzShellCountFinite" \notin established
MoufangTheoremNotEstablished == "MoufangTheorem" \notin established
N3BaselineGridNotEstablished == "N3BaselineGrid" \notin established
N3PoissonHeuristicNotEstablished == "N3PoissonHeuristic" \notin established
QuaternionDoublingNotEstablished == "QuaternionDoubling" \notin established
QuaternionSplitIffConicNotEstablished == "QuaternionSplitIffConic" \notin established
RankLawDegenerateNotEstablished == "RankLawDegenerate" \notin established
RankLawExhaustiveF3NotEstablished == "RankLawExhaustiveF3" \notin established
RankLawNondegenerateNotEstablished == "RankLawNondegenerate" \notin established
WallConjugacyNotEstablished == "WallConjugacy" \notin established
WordDefectEquivarianceNotEstablished == "WordDefectEquivariance" \notin established
WordDefectG2DataNotEstablished == "WordDefectG2Data" \notin established
WordDefectLengthThreeClassicalNotEstablished == "WordDefectLengthThreeClassical" \notin established
WordDefectNotClassicalNotEstablished == "WordDefectNotClassical" \notin established
ZeroDivisorCertificateSoundnessNotEstablished == "ZeroDivisorCertificateSoundness" \notin established
ZornPeirceNotEstablished == "ZornPeirce" \notin established

====
