---- MODULE NoveltyLedger ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
(* Repository: larsbx/novelty-lab. *)
(* Results are named proof records. Requires is one-way dependency, never a *)
(* converse implication. ProvedDef holds the accepted in-repository records, *)
(* ImportedDef the accepted imported theorems, BoundedDef the bounded        *)
(* experiments, WithdrawnDef the withdrawn claims.                           *)
EXTENDS ProofArchitecture

ResultSet == {
    "DivisionCertificateSoundness",
    "HilbertSymbolFormula",
    "HurwitzShellCount",
    "HurwitzShellCountFinite",
    "N3BaselineGrid",
    "N3PoissonHeuristic",
    "QuaternionSplitIffConic",
    "ZeroDivisorCertificateSoundness"
}

RequiresDef == [r \in ResultSet |->
    CASE r = "DivisionCertificateSoundness" -> {"HilbertSymbolFormula", "QuaternionSplitIffConic"}
      [] r = "HilbertSymbolFormula" -> {}
      [] r = "HurwitzShellCount" -> {}
      [] r = "HurwitzShellCountFinite" -> {}
      [] r = "N3BaselineGrid" -> {}
      [] r = "N3PoissonHeuristic" -> {}
      [] r = "QuaternionSplitIffConic" -> {}
      [] r = "ZeroDivisorCertificateSoundness" -> {}]

ProvedDef == {
    "HurwitzShellCountFinite"
}

ImportedDef == {}

BoundedDef == {
    "N3BaselineGrid"
}

WithdrawnDef == {}

NoAssumptions == {}
ImportsAssumed == ImportedDef

(* Observables: one per result, asserting that it is not established. A model *)
(* lists those its assumptions leave unreachable; TLC then checks the closure.  *)
DivisionCertificateSoundnessNotEstablished == "DivisionCertificateSoundness" \notin established
HilbertSymbolFormulaNotEstablished == "HilbertSymbolFormula" \notin established
HurwitzShellCountNotEstablished == "HurwitzShellCount" \notin established
HurwitzShellCountFiniteNotEstablished == "HurwitzShellCountFinite" \notin established
N3BaselineGridNotEstablished == "N3BaselineGrid" \notin established
N3PoissonHeuristicNotEstablished == "N3PoissonHeuristic" \notin established
QuaternionSplitIffConicNotEstablished == "QuaternionSplitIffConic" \notin established
ZeroDivisorCertificateSoundnessNotEstablished == "ZeroDivisorCertificateSoundness" \notin established

====
