---- MODULE NoveltyLedger ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
(* Repository: larsbx/novelty-lab. *)
(* Results are named proof records. Requires is one-way dependency, never a *)
(* converse implication. ProvedDef holds the accepted in-repository records, *)
(* ImportedDef the accepted imported theorems, BoundedDef the bounded        *)
(* experiments, WithdrawnDef the withdrawn claims.                           *)
EXTENDS ProofArchitecture

ResultSet == {
    "ArtinTheorem",
    "CompositionIdentities",
    "DefectCensus",
    "DefectFixesQuaternionSubalgebra",
    "DefectRankLaw",
    "DefectSpecialOrthogonal",
    "DefectStratifiedCollisions",
    "DivisionCertificateSoundness",
    "HilbertSymbolFormula",
    "HurwitzShellCount",
    "HurwitzShellCountFinite",
    "N3BaselineGrid",
    "N3PoissonHeuristic",
    "QuaternionSplitIffConic",
    "RankLawExhaustiveF3",
    "ZeroDivisorCertificateSoundness"
}

RequiresDef == [r \in ResultSet |->
    CASE r = "ArtinTheorem" -> {}
      [] r = "CompositionIdentities" -> {}
      [] r = "DefectCensus" -> {}
      [] r = "DefectFixesQuaternionSubalgebra" -> {"CompositionIdentities", "ArtinTheorem"}
      [] r = "DefectRankLaw" -> {"DefectFixesQuaternionSubalgebra"}
      [] r = "DefectSpecialOrthogonal" -> {}
      [] r = "DefectStratifiedCollisions" -> {}
      [] r = "DivisionCertificateSoundness" -> {"HilbertSymbolFormula", "QuaternionSplitIffConic"}
      [] r = "HilbertSymbolFormula" -> {}
      [] r = "HurwitzShellCount" -> {}
      [] r = "HurwitzShellCountFinite" -> {}
      [] r = "N3BaselineGrid" -> {}
      [] r = "N3PoissonHeuristic" -> {}
      [] r = "QuaternionSplitIffConic" -> {}
      [] r = "RankLawExhaustiveF3" -> {}
      [] r = "ZeroDivisorCertificateSoundness" -> {}]

ProvedDef == {
    "HurwitzShellCountFinite",
    "RankLawExhaustiveF3"
}

ImportedDef == {
    "ArtinTheorem",
    "CompositionIdentities"
}

BoundedDef == {
    "DefectCensus",
    "N3BaselineGrid"
}

WithdrawnDef == {}

NoAssumptions == {}
ImportsAssumed == ImportedDef

(* Observables: one per result, asserting that it is not established. A model *)
(* lists those its assumptions leave unreachable; TLC then checks the closure.  *)
ArtinTheoremNotEstablished == "ArtinTheorem" \notin established
CompositionIdentitiesNotEstablished == "CompositionIdentities" \notin established
DefectCensusNotEstablished == "DefectCensus" \notin established
DefectFixesQuaternionSubalgebraNotEstablished == "DefectFixesQuaternionSubalgebra" \notin established
DefectRankLawNotEstablished == "DefectRankLaw" \notin established
DefectSpecialOrthogonalNotEstablished == "DefectSpecialOrthogonal" \notin established
DefectStratifiedCollisionsNotEstablished == "DefectStratifiedCollisions" \notin established
DivisionCertificateSoundnessNotEstablished == "DivisionCertificateSoundness" \notin established
HilbertSymbolFormulaNotEstablished == "HilbertSymbolFormula" \notin established
HurwitzShellCountNotEstablished == "HurwitzShellCount" \notin established
HurwitzShellCountFiniteNotEstablished == "HurwitzShellCountFinite" \notin established
N3BaselineGridNotEstablished == "N3BaselineGrid" \notin established
N3PoissonHeuristicNotEstablished == "N3PoissonHeuristic" \notin established
QuaternionSplitIffConicNotEstablished == "QuaternionSplitIffConic" \notin established
RankLawExhaustiveF3NotEstablished == "RankLawExhaustiveF3" \notin established
ZeroDivisorCertificateSoundnessNotEstablished == "ZeroDivisorCertificateSoundness" \notin established

====
